#!/usr/bin/env python3

import sys

import click

from calm import Calm


@click.group()
def cli():
    pass

@cli.command()
@click.argument('question', type=str)
def ask(question):
    "Ask a question"
    calm = Calm()
    answer = calm.answer(question)
    print(answer)

@cli.command()
def api():
    "Run the API (compatible w/ OpenAI)"
    calm = Calm()
    calm.api()

if __name__ == "__main__":
    if len(sys.argv) == 1:
        cli.main(['--help'])
    else:
        cli()
